export const language = {
  english: {
    signIn: "Sign In",
    signUp: "Sign Up",
    signUpPage: "Sign Up Page",
    signInPage: "Sign In Page",
    existingUser: "Existing User ? Please Sign In...",
    newToNetflix: "New to netflix ? Please Sign Up Now....",
    play: "Play",
    moreInfo: "More Info",
    yourNextWatch: "Your Next Watch",
    popular: "Popular",
    topRated: "Top Rated",
    upcoming: "Upcoming",
  },
  telugu: {
    signIn: "సైన్ ఇన్ ",
    signUp: "సైన్ అప్ ",
    signUpPage: "సైన్ అప్ పేజీ",
    signInPage: "సైన్ ఇన్ పేజీ",
    existingUser: "ఇప్పటికే ఉన్న వినియోగదారు? దయచేసి సైన్ ఇన్ చేయండి...",
    newToNetflix: "నెట్‌ఫ్లిక్స్‌కి కొత్త? దయచేసి ఇప్పుడే సైన్ అప్ చేయండి....",
    play: "ప్రారంభం",
    moreInfo: "సమాచారం",
    yourNextWatch: "మీ తదుపరి వాచ్",
    popular: "జనాదరణ పొందినది",
    topRated: "టాప్ రేటింగ్",
    upcoming: "రాబోయేది",
  },
  hindi: {
    signIn: "दाखिल करना",
    signUp: "साइन अप",
    signUpPage: "साइन अप पेज",
    signInPage: "साइन इन पेज",
    existingUser: "मौजूदा उपयोगकर्ता? साइन इन करें...",
    newToNetflix: "नेटफ्लिक्स पर नए हैं? कृपया अभी साइन अप करें....",
    play: "शुरू",
    moreInfo: "और जानकारी",
    yourNextWatch: "आपकी अगली घड़ी",
    popular: "लोकप्रिय",
    topRated: "टॉप रेटेड",
    upcoming: "आगामी",
  },
};
